### ISSUE TITLE
firebase_messaging_auto_init_enabled  flag does not work

### ISSUE THREAD

**Issue by shubhamvashisht** [firebase/quickstart-android#467]
Describe your environment

  * Android device: Motorola G4 Plus
  * Android OS version: & 7.0
  * Google Play Services version: 12.5.21
  * Firebase/Play Services SDK version: 12.0.1
  
Describe the problem:
As mentioned in the docs to prevent auto initialisation of fcm tokens we may add ```firebase_messaging_auto_init_enabled``` flag to be ```false``` in ```AndroidManifest.xml```.

```        <!--Disables the auto init of FCM-->
        <meta-data android:name="firebase_messaging_auto_init_enabled"
            android:value="false" /> 
```

 but this does not seem to work as token is still being generated automatically when the app starts.
#### Steps to reproduce:

  1. Add this to manifest.xml and token would still generate without even initialising the firebasemessaging again at runtime.

**Comment by BulatMukhutdinov** [comment]
The same problem

**Comment by kroikie** [comment]
Thanks for flagging this issue @shubhamvashisht and @BulatMukhutdinov I'm digging into this further I'll report back here with an update.

**Comment by kroikie** [comment]
You also need to disable analytics which also uses Firebase Instance ID. So the required metadata would be:

```
<meta-data android:name="firebase_messaging_auto_init_enabled" android:value="false"/>
<meta-data android:name="firebase_analytics_collection_enabled" android:value="false" />
```

Note however that `15.0.0` is required for `firebase_analytics_collection_enabled` field, it existed previously however a bug was fixed in `15.0.0`.

**Comment by ninovanhooff** [comment]
Setting the boolean programmatically works as expected without workaround, I presume? 

https://firebase.google.com/docs/reference/android/com/google/firebase/messaging/FirebaseMessaging.html#setAutoInitEnabled(boolean)

**Comment by kroikie** [comment]
Correct there is a possibility that the token will be generated before the code used for setting to false is run. So if you want to ensure that it does not get generated at all use version 15 or higher

**Comment by alizeyn** [comment]
I have both 
```
<meta-data android:name="firebase_messaging_auto_init_enabled" android:value="false"/>
<meta-data android:name="firebase_analytics_collection_enabled" android:value="false" />
```
in my Manifest.xml but still not working.

firebase-core:16.0.8
firebase-messaging:17.6.0

**Comment by zarkooroz** [comment]
Seems like I have the same issue. Also have both meta-data in manifest.

firebaseCoreVersion = '16.0.7'
firebaseMessagingVersion = '17.4.0'

**Comment by UserSty** [comment]
I have the same issue. Also have both meta-data in the manifest.

playServicesBase = '16.1.0'
firebaseCoreVersion = '16.0.7'
firebaseMessagingVersion = '17.4.0'

Can you help?
